#!/usr/bin/env bash

SHIP=satnum-maptux
LOCKFILE="$HOME/.dlock/$SHIP.lock"

if [ ! -e $LOCKFILE ]; then
#  ~/bin/urbit

source ~/.profile

ID=$(sudo docker run -d -i -t $SHIP /.urbit-exec)
echo $ID > $LOCKFILE
sudo docker attach $ID
sudo docker commit $ID $SHIP > $LOCKFILE

  ~/bin/init-urb-stop
else
  echo "LOCK FILE EXISTS ALREADY... quitting"
fi
