#!/usr/bin/env bash
set -e

SHIP=hatfes-satzod
CONT=hatfes
LOCKFILE="$HOME/.dlock/$SHIP.lock"

if [ ! -e $LOCKFILE ]; then
#  ~/bin/urbit

source ~/.profile
docker rm $CONT || /bin/true
ID=$(docker run --name $CONT -d -i -t $SHIP /.urbinit)
echo $ID > $LOCKFILE
#docker attach $ID
docker attach $CONT
docker commit $CONT $SHIP > $LOCKFILE

  ~/bin/init-yacht-stop $SHIP
else
  echo "LOCK FILE EXISTS ALREADY... quitting"
fi
