#!/usr/bin/env bash

#SHIP=magsup-sogdep
SHIP=novfes-lodzod-nolpun-panfel
LOCKFILE="$HOME/.dlock/$SHIP.lock"

if [ ! -e $LOCKFILE ]; then
#  ~/bin/urbit

source ~/.profile

ID=$(docker run -d -i -t $SHIP)
echo $ID > $LOCKFILE
sudo docker attach $ID
sudo docker commit $ID $SHIP > $LOCKFILE

  ~/bin/init-yacht-stop
else
  echo "LOCK FILE EXISTS ALREADY... quitting"
fi
