#!/usr/bin/env bash

#LOCKFILE="$HOME/.dlock/magsup-sogdep.lock"
LOCKFILE="$HOME/.dlock/novfes-lodzod-nolpun-panfel.lock"

if [ -e $LOCKFILE ]; then
  rm $LOCKFILE
else
  echo "no urb is running (no action taken)"
fi
