FROM yebyen/baseimage:amd64
RUN /usr/bin/apt-get update
RUN /usr/bin/apt-get -y dist-upgrade
RUN /usr/bin/apt-get -y install apt-utils dialog libterm-readline-perl-perl libgmp3-dev libsigsegv-dev openssl libssl-dev libncurses5-dev git make exuberant-ctags wget screen tmux unzip gcc g++
